import type { Metadata } from 'next'
import './globals.css'
import { Header } from '@/components/layout/header'
import { Nunito } from 'next/font/google'
import { Toaster } from 'sonner'
import { Providers } from './providers'

const nunito = Nunito({
	subsets: ['latin']
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
}

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en'>
			<body className={nunito.className}>
				<Providers>
					<Toaster />
					<Header />
					<main>{children}</main>
				</Providers>
			</body>
		</html>
	)
}
